name: Flutter Android Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v3

      # Step 2: Set up Java (using Java 11, as Android Gradle Plugin 8+ is compatible with Java 11+)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # Step 3: Set up the Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # Step 4: Set up Gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # Step 5: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'
          channel: 'stable'
          cache: true

      # Step 6: Create local.properties
      - name: Create local.properties
        run: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties
          echo "flutter.sdk=$FLUTTER_HOME" >> android/local.properties

      # Step 7: Ensure Gradlew is executable
      - name: Make Gradlew Executable
        run: chmod +x android/gradlew

      # Step 8: Add AndroidX properties to gradle.properties
      - name: Ensure AndroidX is enabled
        run: |
          echo "android.useAndroidX=true" >> android/gradle.properties
          echo "android.enableJetifier=true" >> android/gradle.properties

      # Step 9: Get Flutter dependencies
      - name: Get dependencies
        run: flutter pub get

      # Step 10: Clean Gradle cache
      - name: Clean Gradle
        run: cd android && ./gradlew clean

      # Step 11: Build the release APK
      - name: Build APK
        run: flutter build apk --release

      # Step 12: Upload APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          
  ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'
          channel: 'stable'
          cache: true
      - name: Get dependencies
        run: flutter pub get
      - name: Install Pods
        run: |
          cd ios
          pod install
      - name: Build iOS for devices
        run: |
          flutter clean
          flutter build ios --debug --simulator
          cd build/ios/iphonesimulator
          zip -r simulator-build.zip Runner.app/
      - name: Upload simulator build
        uses: actions/upload-artifact@v3
        with:
          name: iphone-simulator-build
          path: build/ios/iphonesimulator/simulator-build.zip
